environment:		
  - nodejs_version: "6"

artifacts:
  - path: jsreport.exe
    name: jsreport.exe

install:  
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version  
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - appveyor-retry npm install
  - appveyor-retry npm install jsreport-compile -p
  - "node_modules/.bin/jsreport-compile.cmd"

test_script:  
  - node --version
  - npm --version  
  - npm test

build: off
