install:
  - node --version
  - npm --version  
  - npm install
  - npm install jsreport-compile -p
  - "node_modules/.bin/jsreport-compile.cmd"

test_script:  
  - node --version
  - npm --version  
  - npm test

build: off
