os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

sudo: required
dist: trusty

language: node_js

node_js:
  - '6'
  - '4'

before_install:
  - if [[ `node -v` == v4* ]]; then npm i -g npm@2; fi

before_deploy:
  - if [[ `npm -v` == 1* ]] || [[ `npm -v` == 2* ]]; then npm i -g npm@3; fi
  - "cp example.config.json dev.config.json"
  - "cp executable-license.txt license.txt"
  - "npm install jsreport-compile"
  - "npm run compile"
  - "tar -czvf jsreport-$TRAVIS_OS_NAME.tar.gz jsreport license.txt"
  - "npm install phantomjs-exact-2-1-1"
  - "env phantom:defaultPhantomjsVersion=2.1.1 npm run compile"
  - "tar -czvf jsreport-$TRAVIS_OS_NAME-ph2.tar.gz jsreport license.txt"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TlV2eBd3M16e1LmsBR+8H982L1z2Hn5LghbgpwkIvxxBfjo7uuMYSwoL0ihY36Q7nGMYWvCUNn3tPZCeGolXQOdKbwOggjDMpk23rKpTj7D5IL/84Izcz0iQpugi0CZe4OcmoitLIa9h/2x9oGUJAbdmqQawGdHkuASa25tb+h4=
  file:
    - jsreport-$TRAVIS_OS_NAME.tar.gz
    - jsreport-$TRAVIS_OS_NAME-ph2.tar.gz
  on:
    tags: true
